// Objective-C API for talking to gomobiletest Go package.
//   gobind -lang=objc gomobiletest
//
// File is generated by gobind. Do not edit.

#ifndef __GoGomobiletest_H__
#define __GoGomobiletest_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString* GoGomobiletestGenearateOtpFromURL(NSString* url);

FOUNDATION_EXPORT NSString* GoGomobiletestGreetings(NSString* name);

#endif
